### ISSUE TITLE
Restarting from file & MPI error

### ISSUE THREAD

**Issue by camierjs** [cselab/smarties#5]
Hi,

I'm evaluating the library which seems promising: thank you for sharing it!

I hitting an error both on `macos` and `Linux`, trying to train/run `cart_pole_cpp`.

The first launch is done with `smarties.py --runprefix . -r training cart_pole_cpp`.

When I try to restart with `smarties.py --runprefix . -r training --restart training cart_pole_cpp`, I'm getting:
```Parameters restart file training/agent_00_net_weights.raw not found.
Parameters restart file training/agent_00_net_tgt_weights.raw not found.
Parameters restart file training/agent_00_net_1stMom.raw not found.
Parameters restart file training/agent_00_net_2ndMom.raw not found.
```
and most of the missing files seem prefixed with `restarted_`.

Renaming them allow to try to launch an evaluation: 
`smarties.py --runprefix . -r running --restart training --nEvalEpisodes 1`,
which triggers another error:
```
App recvd end-of-training signal.
*** An error occurred in MPI_Comm_free
*** reported by process [3611164673,0]
*** on communicator MPI_COMM_SELF
*** MPI_ERR_COMM: invalid communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

Anything obvious I'm missing?

Thank you for your help.

John

**Comment by camierjs** [comment]
Waiting for the files to be outputted helped with the first part.

Testing `environment_app_comm` in `ExecutionInfo` not to be `MPI_COMM_SELF` allowed to avoid the second.

**Comment by novatig** [comment]
Hi, sorry for the delay.

Thank you for finding this bug!
I got so used with "inelegant exits"* that I never minded that.
I will push a fix.

*(Just aborting from the master to avoid having to check termination in client code.)

**Comment by novatig** [comment]
I pushed an update, thanks again.

You also should be able to do:
smarties.py cart_pole_cpp  -r training
and then:
smarties.py cart_pole_cpp  -r evaluating --restart training --nEvalEpisodes 1
Both directories will be in $(SMARTIES_ROOT)/runs

**Comment by camierjs** [comment]
Awesome, thank you!
