### ISSUE TITLE
[Save/Restart] MemoryBuffer

### ISSUE THREAD

**Issue by camierjs** [cselab/smarties#6]
When saving/restarting, there seems to be a shift of `1` for `currStep` when `MemoryBuffer::save`ing and `Learner::initializeLearner` is getting back the `currStep`. 

The `currStep % settings.saveFreq` condition won't hold anymore and the restart run does not save the files.

Adjusting `doneGradSteps` allows to get it right again.

Thank you for your help!

**Comment by novatig** [comment]
Thank you, I fixed the related bug.

**Comment by camierjs** [comment]
Great: thank you again for the quick fix!
