### ISSUE TITLE
question about "cart_pole_f90"

### ISSUE THREAD

**Issue by jiatingdaole1109** [cselab/smarties#9]
Hello, I got some errors when trying to run /cart_pole_f90/setup.sh in the shell. It seems that there is something wrong with the link process. But in /cart_pole_cpp, it works fine and no errors happend. The error message is showed below. Otherwise, I wonder if there are any ways to visualize the trained model to get a direct result, instead of plotting data cruves.
Could you please give me some advice? Looking forward to your reply. Thanks a lot! 

dyfluid@dyfluid:~/Desktop/smarties/apps/cart_pole_f90$ ./setup.sh 
mpic++  -o exec main.o app_main.o cart_pole.o smarties.o -lgfortran -lmpifort -L/home/dyfluid/Desktop/smarties/lib -lsmarties
/usr/bin/ld: main.o: in function `main':
main.cpp:(.text.startup+0x99): undefined reference to `smarties::Engine::run(std::function<void (smarties::Communicator*, int, int, char**)> const&)'
/usr/bin/ld: app_main.o: in function `app_main':
app_main.f90:(.text+0x1c3): undefined reference to `smarties_setStateActionDims'
/usr/bin/ld: app_main.f90:(.text+0x201): undefined reference to `smarties_setActionScales'
/usr/bin/ld: app_main.f90:(.text+0x22b): undefined reference to `smarties_setStateObservable'
/usr/bin/ld: app_main.f90:(.text+0x2a2): undefined reference to `smarties_setStateScales'
/usr/bin/ld: app_main.f90:(.text+0x354): undefined reference to `smarties_sendInitState'
/usr/bin/ld: app_main.f90:(.text+0x361): undefined reference to `smarties_sendState'
/usr/bin/ld: app_main.f90:(.text+0x375): undefined reference to `smarties_recvAction'
/usr/bin/ld: app_main.f90:(.text+0x4b1): undefined reference to `smarties_sendTermState'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:35: exec] Error 1
make: *** [Makefile:31: main-build] Error 2
cp: cannot stat 'exec': No such file or directory

**Comment by novatig** [comment]
Hello,

I was not the author of the F90 example, so I can be of very limited help.
The setup script is not meant to be called by the user. It's how the user tells the python launcher (`smarties.py`) how to set up the environment.
Were you able to compile the library without issues? (e.g. `cd $(SMARTIES_ROOT)/makefiles/ && make`)
Can you compile the app? (e.g. `cd $(SMARTIES_ROOT)/apps/cart_pole_f90/ && make`)

Regarding the visualization of the model, usually this is done qualitatively through the environment. For example, you may call `smarties.py [...] --nEvalEpisodes N` and collect in the environment application metrics about the agent, or snapshots of the simulation.

**Comment by jiatingdaole1109** [comment]
It's really grateful to have your reply @novatig.  After trying to rerunning the makefile in `$(SMARTIES_ROOT)/makefiles`, the link problem was solved. 
Actuallly I've read your paper about fish schooling, which is really inspiring. Currently I'm also trying to use RL in my own problem. But I'm a newbie in RL, so I'd like to know if it would bother you if I directly ask you questions about `smarties` through gmail?
